- name: NGINX config directory
  file:
    path: /tmp/nginx
    state: directory

- name: NGINX configuration setup
  template:
    src: "/home/runner/work/DCE-ukol01/DCE-ukol01/ansible/roles/load_balancer/templates/nginx.conf.j2"
    dest: /tmp/nginx/nginx.conf

- name: Install NGINX - Load Balancer
  docker_container:
    name: webserver
    image: nginx:latest
    state: started
    restart_policy: unless-stopped
    pull: yes
    ports:
    - "80:80"
    volumes:
    - /tmp/nginx/nginx.conf:/etc/nginx/nginx.conf
