- name: Environment setup
  hosts: all
  tasks:
    - name: Run preparation tasks
      include_tasks: roles/env.yml

- name: Backends setup
  hosts: backends
  vars:
    ansible_python_interpreter: /opt/venv/bin/python
  tasks:
    - name: Backends setup in environment
      include_tasks: roles/backends/task/main.yml

- name: Load balancer setup
  hosts: loadBalancer
  vars:
    ansible_python_interpreter: /opt/venv/bin/python
  tasks:
    - name: Load balancer setup in environment
      include_tasks: roles/loadBalancer/task/main.yml
